language: node_js
notifications:
  on_success: never
  on_failure: never
node_js:
  - "stable"
before_script:
  - snyk auth 1bd0a425-8b1e-4c45-a5b5-33506f6fd219
script:
  - npm run coverage
services:
  - mongodb
after_success:
  - npm run coveralls
  - snyk monitor
after_deploy:
  - snyk monitor